### ISSUE TITLE
Error on installing dynamic plugin 'studio'

### ISSUE THREAD

**Issue by IgorTimoshenko** [orientechnologies/orientdb-docker#11]
Hello!

I have the error with installing dynamic plugin `studio` when I try to attach persistent volumes.

```sh
# docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```

```sh
# docker-composer version
docker-compose version 1.7.0, build 0d7bf73
docker-py version: 1.8.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1j 15 Oct 2014
```

```yaml
# docker-compose.yml
orientdb:
    ports:
        - 2424:2424
        - 2480:2480
    volumes:
        - /var/orientdb/backup:/orientdb/backup
        - /var/orientdb/config:/orientdb/config
        - /var/orientdb/databases:/orientdb/databases
    extends:
        file: common.yml
        service: orientdb
```

```sh
docker-compose up -d
docker-compose logs orientdb

Attaching to foo_orientdb
foo_orientdb | 
foo_orientdb | OrientDB console v.2.2.0 (build develop@r79d281140b01c0bc3b566a46a64f1573cb359783; 2016-05-18 14:14:32+0000) www.orientdb.com
foo_orientdb | Type 'help' to display all the supported commands.
foo_orientdb | Installing extensions for GREMLIN language v.2.6.0
foo_orientdb | 
foo_orientdb | orientdb> create database plocal:/orientdb/databases/foo root bar plocal graph
foo_orientdb | 
foo_orientdb | Creating database [plocal:/orientdb/databases/foo] using the storage type [plocal]...
foo_orientdb | Database created successfully.
foo_orientdb | 
foo_orientdb | Current database is: plocal:/orientdb/databases/foo
foo_orientdb |            .                                          
foo_orientdb |           .`        `                                 
foo_orientdb |           ,      `:.                                  
foo_orientdb |          `,`    ,:`                                   
foo_orientdb |          .,.   :,,                                    
foo_orientdb |          .,,  ,,,                                     
foo_orientdb |     .    .,.:::::  ````                                 :::::::::     :::::::::   
foo_orientdb |     ,`   .::,,,,::.,,,,,,`;;                      .:    ::::::::::    :::    :::  
foo_orientdb |     `,.  ::,,,,,,,:.,,.`  `                       .:    :::      :::  :::     ::: 
foo_orientdb |      ,,:,:,,,,,,,,::.   `        `         ``     .:    :::      :::  :::     ::: 
foo_orientdb |       ,,:.,,,,,,,,,: `::, ,,   ::,::`   : :,::`  ::::   :::      :::  :::    :::  
foo_orientdb |        ,:,,,,,,,,,,::,:   ,,  :.    :   ::    :   .:    :::      :::  :::::::     
foo_orientdb |         :,,,,,,,,,,:,::   ,,  :      :  :     :   .:    :::      :::  :::::::::   
foo_orientdb |   `     :,,,,,,,,,,:,::,  ,, .::::::::  :     :   .:    :::      :::  :::     ::: 
foo_orientdb |   `,...,,:,,,,,,,,,: .:,. ,, ,,         :     :   .:    :::      :::  :::     ::: 
foo_orientdb |     .,,,,::,,,,,,,:  `: , ,,  :     `   :     :   .:    :::      :::  :::     ::: 
foo_orientdb |       ...,::,,,,::.. `:  .,,  :,    :   :     :   .:    :::::::::::   :::     ::: 
foo_orientdb |            ,::::,,,. `:   ,,   :::::    :     :   .:    :::::::::     ::::::::::  
foo_orientdb |            ,,:` `,,.                                  
foo_orientdb |           ,,,    .,`                                  
foo_orientdb |          ,,.     `,                                          GRAPH DATABASE  
foo_orientdb |        ``        `.                                                          
foo_orientdb |                  ``                                          orientdb.com
foo_orientdb |                  `                                    
foo_orientdb | 
foo_orientdb | 2016-05-23 14:07:53:691 WARNI Not enough physical memory available for DISKCACHE: 2,002MB (heap=494MB direct=524,288MB). Set lower Maximum Heap (-Xmx setting on JVM) and restart OrientDB. Now running with DISKCACHE=256MB [orientechnologies]
foo_orientdb | 2016-05-23 14:07:53:696 INFO  OrientDB config DISKCACHE=256MB (heap=494MB direct=524,288MB os=2,002MB) [orientechnologies]
foo_orientdb | 2016-05-23 14:07:53:956 INFO  Loading configuration from: /orientdb/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
foo_orientdb | 2016-05-23 14:07:54:525 SEVER Server configuration file not found: /orientdb/config/orientdb-server-config.xml [OServerConfigurationLoaderXml]
foo_orientdb | 2016-05-23 14:07:54:529 INFO  OrientDB Server v2.2.0 (build develop@r79d281140b01c0bc3b566a46a64f1573cb359783; 2016-05-18 14:14:32+0000) is starting up... [OServer]
foo_orientdb | 2016-05-23 14:07:54:542 INFO  Databases directory: /orientdb/databases [OServer]
foo_orientdb | 2016-05-23 14:07:54:793 INFO  {db=OSystem} Creating the system database 'OSystem' for current server [OSystemDatabase]
foo_orientdb | 2016-05-23 14:07:55:195 INFO  {db=OSystem} Saving Command Cache config for db: OSystem [OCommandCacheSoftRefs]
foo_orientdb | 2016-05-23 14:07:56:675 SEVER ODefaultServerSecurity.loadConfig() Could not access the security JSON file: /orientdb/config/security.json [ODefaultServerSecurity]
foo_orientdb | 2016-05-23 14:07:56:819 INFO  Listening binary connections on 127.0.0.1:2424 (protocol v.36, socket=default) [OServerNetworkListener]
foo_orientdb | 2016-05-23 14:07:56:825 WARNI Found ORIENTDB_ROOT_PASSWORD variable, using this value as root's password [OServer]
foo_orientdb | 2016-05-23 14:07:57:920 INFO  Installing dynamic plugin 'studio-2.2.zip'... [OServerPluginManager]Error on installing dynamic plugin 'studio'
foo_orientdb | com.orientechnologies.orient.core.exception.OConfigurationException: HTTP listener not registered while installing Static Content command
foo_orientdb | 	at com.orientechnologies.orient.server.plugin.OServerPluginManager.registerStaticDirectory(OServerPluginManager.java:215)
foo_orientdb | 	at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:364)
foo_orientdb | 	at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:202)
foo_orientdb | 	at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:290)
foo_orientdb | 	at com.orientechnologies.orient.server.plugin.OServerPluginManager.startup(OServerPluginManager.java:93)
foo_orientdb | 	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1135)
foo_orientdb | 	at com.orientechnologies.orient.server.OServer.activate(OServer.java:390)
foo_orientdb | 	at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
foo_orientdb | 
foo_orientdb | 2016-05-23 14:07:57:932 SEVER ODefaultServerSecurity.onAfterActivate() Configuration document is empty [ODefaultServerSecurity]
```

Any ideas? Thanks!

**Comment by robfrank** [comment]
If you provide a config volume you should provide a full configuration files set inside that will overrides the default config folder inside the container. If you don't need it, and can rely on the default conf, don't provide a volume with config. 
This is not related with ODB, but it is more an " how Docker wokrs": volumes handling is the first beast to fight. Next is the networking :)

**Comment by MadisonStiefel** [comment]
how do you do that within the template?
