### ISSUE TITLE
Browser asks for authentication when I mount localhost config and database folders

### ISSUE THREAD

**Issue by sharang17** [orientechnologies/orientdb-docker#44]
My docker image uses an ubuntu Xenial base image with java, I installed orientdb to /opt/orientdb in the container thus formed, after which I mounted a database and config folder from my localhost to the container. I mapped the 2480 port to the studio and then run localhost:2480 to access the studio. I can see the databases I had created before, but when I login using the credentials I had set before, which are present in the config file, I get a popup in the browser which asks me to authenticate. I don't know what credentials to add there, even the root login doesn't work. Below is the error on the console.

```
Exception `54384099` in storage `plocal:/opt/orientdb/databases/OperatingEvents`: 2.2.33 (build 77584cd6827f647cf4aa231cf27bd6f10bc04e2c, branch 2.2.x)
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/opt/orientdb/databases/OperatingEvents' with mode=rw
	DB name="OperatingEvents"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:323)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:259)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:988)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:958)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:945)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.authenticate(OServerCommandAuthenticatedDbAbstract.java:163)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.beforeExecute(OServerCommandAuthenticatedDbAbstract.java:123)
	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetConnect.beforeExecute(OServerCommandGetConnect.java:50)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:170)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:629)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
```

**Comment by palabadi** [comment]
Might be your OS (possibly not your browser) asking for permission to share the local folder with docker
