### ISSUE TITLE
OConfigurationException: HTTP listener not registered while installing Static Content command

### ISSUE THREAD

**Issue by chris-martin** [orientechnologies/orientdb-docker#5]
This is the output I get when I run the 2.1.5 image:

```
2015-11-03 00:11:07:364 INFO  OrientDB auto-config DISKCACHE=5,110MB (heap=455MB os=7,613MB disk=99,920MB) [orientechnologies]
2015-11-03 00:11:07:463 INFO  Loading configuration from: /orientdb/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2015-11-03 00:11:07:823 INFO  OrientDB Server v2.1.5 (build 2.1.x@r; 2015-10-29 16:54:25+0000) is starting up... [OServer]
2015-11-03 00:11:07:856 INFO  Databases directory: /orientdb/databases [OServer]
2015-11-03 00:11:07:892 INFO  Listening binary connections on 127.0.0.1:2424 (protocol v.32, socket=default) [OServerNetworkListener]
2015-11-03 00:11:07:896 INFO  Installing dynamic plugin 'studio-2.1.zip'... [OServerPluginManager]Error on installing dynamic plugin 'studio'
com.orientechnologies.orient.core.exception.OConfigurationException: HTTP listener not registered while installing Static Content command
     at com.orientechnologies.orient.server.plugin.OServerPluginManager.registerStaticDirectory(OServerPluginManager.java:215)
     at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:366)
     at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:202)
     at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:292)
     at com.orientechnologies.orient.server.plugin.OServerPluginManager.startup(OServerPluginManager.java:93)
     at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:939)
     at com.orientechnologies.orient.server.OServer.activate(OServer.java:346)
     at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)
```

I'm just trying to use OrientDB for the first time, so I have no idea what's wrong.

**Comment by robfrank** [comment]
Hi,
I run the docker image this way:
    
    docker run --name orientdb_1_nodist -d  \
    -v ~/local/orientdb/node1/databases:/orientdb/databases \
    -v ~/local/orientdb/node1/backup:/orientdb/backup \
    -p 2424:2424 -p 2480:2480 \
    -e ORIENTDB_ROOT_PASSWORD=rootpwd \
    -e ORIENTDB_NODE_NAME=node1 \
    orientdb/orientdb:2.1.5 server.sh

This is the log from docker console

```console

    2015-11-03 11:11:14:197 INFO  OrientDB auto-config DISKCACHE=1,402MB (heap=455MB os=3,905MB disk=221,423MB) [orientechnologies]
2015-11-03 11:11:14:516 INFO  Loading configuration from: /orientdb/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2015-11-03 11:11:15:262 INFO  OrientDB Server v2.1.5 (build 2.1.x@r; 2015-10-29 16:54:25+0000) is starting up... [OServer]
2015-11-03 11:11:15:339 INFO  Databases directory: /orientdb/databases [OServer]
2015-11-03 11:11:15:461 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.32, socket=default) [OServerNetworkListener]
2015-11-03 11:11:15:488 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2015-11-03 11:11:15:657 INFO  Installing dynamic plugin 'studio-2.1.zip'... [OServerPluginManager]
2015-11-03 11:11:15:818 INFO  Installing GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]
2015-11-03 11:11:15:819 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]
2015-11-03 11:11:15:821 INFO  Installing Script interpreter. WARN: authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
```
